<?php $this->headTitle('Home'); ?>

<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Freelancer Tools</span></h1>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>
            <a href="https://docs.zendframework.com/zend-expressive/getting-started/features" target="_blank">
                <i class="fa fa-bolt"></i> Col 1
            </a>
        </h2>
        <p>
            Lipsum.
        </p>
    </div>

    <div class="col-md-4">
        <h2>
            <a href="https://github.com/zendframework/zend-diactoros" target="_blank">
                <i class="fa fa-exchange-alt"></i> Col 2
            </a>
        </h2>
        <p>
            Lipsum.
        </p>
    </div>

    <div class="col-md-4">
        <h2>
            <a href="https://github.com/zendframework/zend-stratigility" target="_blank">
                <i class="fa fa-dot-circle"></i> Col 3
            </a>
        </h2>
        <p>
            Lipsum.
        </p>
    </div>
</div>
